language: node_js
node_js:
  - "14"
  - "16"
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: npm
  email: $NPM_AUTH_EMAIL
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
    branch: master